#!/bin/bash

if [[ ! -d "${HOME}/.bash-aliases-framework" ]];then
  path=""
  if [[ "$1" == "install-script" ]];then
    path="/bash-aliases-framework"
  fi
  ln -s "$(pwd)${path}" "${HOME}/.bash-aliases-framework";
fi

file_path=".bash-aliases-framework/.bash_aliases"

source_1="source \"\${HOME}/${file_path}\""

bash_aliases_path="${HOME}/.bash_aliases"

file_content="$(cat "${bash_aliases_path}")"
IFS=$'\n'
read -rd '' -a lines <<<"${file_content}"

[[ "${lines[*]}" != *"$source_1"* ]] && echo "source \"\${HOME}/${file_path}\"" >> "${bash_aliases_path}" || echo "" >> /dev/null