#!/bin/bash

if [[ ! -d "${HOME}/.bash-aliases-framework" ]];then
  path=""
  if [[ "$1" == "install-script" ]];then
    path="/bash-aliases-framework"
  fi
  ln -s "$(pwd)${path}" "${HOME}/.bash-aliases-framework";
fi

file_path=".bash-aliases-framework/.bash_aliases"

source_1="source \"\${HOME}/${file_path}\""
source_2="source \"~/${file_path}\""

bash_aliases_path="${HOME}/.bash_aliases"
bash_aliases_content="$(cat "${bash_aliases_path}")"

if {
  [[ ! "${bash_aliases_content}" =~ $source_1 ]] &&
  [[ ! "${bash_aliases_content}" =~ $source_2 ]]
};then
  echo "source \"\${HOME}/${file_path}\"" >> "${bash_aliases_path}"
fi